# clash уџёУДётѕЎТќЄС╗Х№╝їТћ»ТїЂУЄфт«џС╣ЅУДётѕЎ№╝їтЈ»С╗ЦТа╣ТЇ«УЄфти▒уџёжюђТ▒ѓТи╗тіаУДётѕЎ
# У»ду╗єТќЄТАБУ»итЈѓУђЃ№╝џhttps://lancellc.gitbook.io/clash/clash-config-file/rule-providers
rules:
  # У┐ЎтЄаСИфС╗Буљєтю░тЮђуЏ┤ТјЦУх░уЏ┤У┐ъ
  - DOMAIN-SUFFIX,github.com,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,google.com.hk,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,telegram.org,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,telesco.pe,­Ъџђ УЄфтіетіажђЪ
  - IP-CIDR,91.108.0.0/16,­Ъџђ УЄфтіетіажђЪ,no-resolve
  - IP-CIDR,109.239.140.0/24,­Ъџђ УЄфтіетіажђЪ,no-resolve
  - IP-CIDR,149.154.160.0/20,­Ъџђ УЄфтіетіажђЪ,no-resolve
  - IP-CIDR6,2001:67c:4e8::/48,­Ъџђ УЄфтіетіажђЪ,no-resolve
  - IP-CIDR6,2001:b28:f23d::/48,­Ъџђ УЄфтіетіажђЪ,no-resolve
  - IP-CIDR6,2001:b28:f23f::/48,­Ъџђ УЄфтіетіажђЪ,no-resolve
  - DOMAIN-SUFFIX,edgedatg.com,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,go.com,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,uk-live,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,bbc.co,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,bbc.com,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,apache.org,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,docker.com,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,elastic.co,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-SUFFIX,elastic.com,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,sci-hub,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,spotify,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,telegram,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,twitter,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,whatsapp,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,youtube,­Ъџђ УЄфтіетіажђЪ
  - DOMAIN-KEYWORD,gfwlist,­Ъџђ УЄфтіетіажђЪ
  - GEOIP,CN,DIRECT
  - DOMAIN-SUFFIX,acl4.ssr,DIRECT
  - DOMAIN-SUFFIX,ip6-localhost,DIRECT
  - DOMAIN-SUFFIX,ip6-loopback,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,localhost,DIRECT